setblock ~-1~~ concretepowder 12
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~
summon lightning_bolt ~-1~~