#main menu scroll
execute @a[scores={main=1}] ~~~ execute @s[scores={main_scroll=1}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §9 COMBAT MENU                §1▐ \n §1▐               §9VISUAL MENU              §1▐ \n §1▐               §9MOVEMENT MENU             §1▐ \n §1▐               §9PLAYER MENU                §1▐ \n §1▐               §9WORLD MENU             §1▐ \n §1▐               §9EXPLOIT MENU             §1▐ \n §1▐               §9MISC MENU                  §1▐ \n §1▐               §9FLIES MENU                 §1▐ \n §1▐               §9GUI MENU                 §1▐ \n §1▐               §9CREDITS MENU             §1▐ \n §1▐               §cADMIN MENU               §1▐ \n §1▐               §9CLOSE MENU               §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={main=1}] ~~~ execute @s[scores={main_scroll=2}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §f⋙COMBAT MENU⋘               §1▐ \n §1▐               §9VISUAL MENU               §1▐ \n §1▐               §9MOVEMENT MENU             §1▐ \n §1▐               §9PLAYER MENU                §1▐ \n §1▐               §9WORLD MENU             §1▐ \n §1▐               §9EXPLOIT MENU             §1▐ \n §1▐               §9MISC MENU                  §1▐ \n §1▐               §9FLIES MENU                 §1▐ \n §1▐               §9GUI MENU                 §1▐ \n §1▐               §9CREDITS MENU             §1▐ \n §1▐               §cADMIN MENU               §1▐ \n §1▐               §9CLOSE MENU               §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={main=1}] ~~~ execute @s[scores={main_scroll=3}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §9 COMBAT MENU                §1▐ \n §1▐              §f⋙VISUAL MENU⋘              §1▐ \n §1▐               §9MOVEMENT MENU             §1▐ \n §1▐               §9PLAYER MENU                §1▐ \n §1▐               §9WORLD MENU             §1▐ \n §1▐               §9EXPLOIT MENU             §1▐ \n §1▐               §9MISC MENU                  §1▐ \n §1▐               §9FLIES MENU                 §1▐ \n §1▐               §9GUI MENU                 §1▐ \n §1▐               §9CREDITS MENU             §1▐ \n §1▐               §cADMIN MENU               §1▐ \n §1▐               §9CLOSE MENU               §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={main=1}] ~~~ execute @s[scores={main_scroll=4}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §9 COMBAT MENU                §1▐ \n §1▐              §9 VISUAL MENU               §1▐ \n §1▐              §f⋙MOVEMENT MENU⋘            §1▐ \n §1▐               §9PLAYER MENU                §1▐ \n §1▐               §9WORLD MENU             §1▐ \n §1▐               §9EXPLOIT MENU             §1▐ \n §1▐               §9MISC MENU                  §1▐ \n §1▐               §9FLIES MENU                 §1▐ \n §1▐               §9GUI MENU                 §1▐ \n §1▐               §9CREDITS MENU             §1▐ \n §1▐               §cADMIN MENU               §1▐ \n §1▐               §9CLOSE MENU               §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={main=1}] ~~~ execute @s[scores={main_scroll=5}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §9 COMBAT MENU                §1▐ \n §1▐              §9 VISUAL MENU               §1▐ \n §1▐              §9 MOVEMENT MENU             §1▐ \n §1▐              §f⋙PLAYER MENU⋘               §1▐ \n §1▐               §9WORLD MENU             §1▐ \n §1▐               §9EXPLOIT MENU             §1▐ \n §1▐               §9MISC MENU                  §1▐ \n §1▐               §9FLIES MENU                 §1▐ \n §1▐               §9GUI MENU                 §1▐ \n §1▐               §9CREDITS MENU             §1▐ \n §1▐               §cADMIN MENU               §1▐ \n §1▐               §9CLOSE MENU               §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={main=1}] ~~~ execute @s[scores={main_scroll=6}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §9 COMBAT MENU                §1▐ \n §1▐              §9 VISUAL MENU               §1▐ \n §1▐              §9 MOVEMENT MENU             §1▐ \n §1▐              §9 PLAYER MENU                §1▐ \n §1▐              §f⋙WORLD MENU⋘            §1▐ \n §1▐               §9EXPLOIT MENU             §1▐ \n §1▐               §9MISC MENU                  §1▐ \n §1▐               §9FLIES MENU                 §1▐ \n §1▐               §9GUI MENU                 §1▐ \n §1▐               §9CREDITS MENU             §1▐ \n §1▐               §cADMIN MENU               §1▐ \n §1▐               §9CLOSE MENU               §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={main=1}] ~~~ execute @s[scores={main_scroll=7}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §9 COMBAT MENU                §1▐ \n §1▐              §9 VISUAL MENU               §1▐ \n §1▐              §9 MOVEMENT MENU             §1▐ \n §1▐              §9 PLAYER MENU                §1▐ \n §1▐               §9WORLD MENU             §1▐ \n §1▐              §f⋙EXPLOIT MENU⋘            §1▐ \n §1▐               §9MISC MENU                  §1▐ \n §1▐               §9FLIES MENU                 §1▐ \n §1▐               §9GUI MENU                 §1▐ \n §1▐               §9CREDITS MENU             §1▐ \n §1▐               §cADMIN MENU               §1▐ \n §1▐               §9CLOSE MENU               §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={main=1}] ~~~ execute @s[scores={main_scroll=8}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §9 COMBAT MENU                §1▐ \n §1▐              §9 VISUAL MENU               §1▐ \n §1▐              §9 MOVEMENT MENU             §1▐ \n §1▐              §9 PLAYER MENU                §1▐ \n §1▐               §9WORLD MENU             §1▐ \n §1▐              §9 EXPLOIT MENU             §1▐ \n §1▐              §f⋙MISC MENU⋘                 §1▐ \n §1▐               §9FLIES MENU                 §1▐ \n §1▐               §9GUI MENU                 §1▐ \n §1▐               §9CREDITS MENU             §1▐ \n §1▐               §cADMIN MENU               §1▐ \n §1▐               §9CLOSE MENU               §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={main=1}] ~~~ execute @s[scores={main_scroll=9}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §9 COMBAT MENU                §1▐ \n §1▐              §9 VISUAL MENU               §1▐ \n §1▐              §9 MOVEMENT MENU             §1▐ \n §1▐              §9 PLAYER MENU                §1▐ \n §1▐               §9WORLD MENU             §1▐ \n §1▐              §9 EXPLOIT MENU             §1▐ \n §1▐              §9 MISC MENU                  §1▐ \n §1▐              §f⋙FLIES MENU⋘                §1▐ \n §1▐               §9GUI MENU                 §1▐ \n §1▐               §9CREDITS MENU             §1▐ \n §1▐               §cADMIN MENU               §1▐ \n §1▐               §9CLOSE MENU               §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={main=1}] ~~~ execute @s[scores={main_scroll=10}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §9 COMBAT MENU                §1▐ \n §1▐              §9 VISUAL MENU               §1▐ \n §1▐              §9 MOVEMENT MENU             §1▐ \n §1▐              §9 PLAYER MENU                §1▐ \n §1▐               §9WORLD MENU             §1▐ \n §1▐              §9 EXPLOIT MENU             §1▐ \n §1▐              §9 MISC MENU                  §1▐ \n §1▐              §9 FLIES MENU                 §1▐ \n §1▐              §f⋙GUI MENU⋘                §1▐ \n §1▐               §9CREDITS MENU             §1▐ \n §1▐               §cADMIN MENU               §1▐ \n §1▐               §9CLOSE MENU               §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={main=1}] ~~~ execute @s[scores={main_scroll=11}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §9 COMBAT MENU                §1▐ \n §1▐              §9 VISUAL MENU               §1▐ \n §1▐              §9 MOVEMENT MENU             §1▐ \n §1▐              §9 PLAYER MENU                §1▐ \n §1▐               §9WORLD MENU             §1▐ \n §1▐              §9 EXPLOIT MENU             §1▐ \n §1▐              §9 MISC MENU                  §1▐ \n §1▐              §9 FLIES MENU                 §1▐ \n §1▐              §9 GUI MENU                 §1▐ \n §1▐              §f⋙CREDITS MENU⋘            §1▐ \n §1▐               §cADMIN MENU               §1▐ \n §1▐               §9CLOSE MENU               §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={main=1}] ~~~ execute @s[scores={main_scroll=12}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §9 COMBAT MENU                §1▐ \n §1▐              §9 VISUAL MENU               §1▐ \n §1▐              §9 MOVEMENT MENU             §1▐ \n §1▐              §9 PLAYER MENU                §1▐ \n §1▐               §9WORLD MENU             §1▐ \n §1▐              §9 EXPLOIT MENU             §1▐ \n §1▐              §9 MISC MENU                  §1▐ \n §1▐              §9 FLIES MENU                 §1▐ \n §1▐              §9 GUI MENU                 §1▐ \n §1▐              §9 CREDITS MENU             §1▐ \n §1▐              §4⋙ADMIN MENU⋘              §1▐ \n §1▐               §9CLOSE MENU               §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={main=1}] ~~~ execute @s[scores={main_scroll=13}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §9 COMBAT MENU                §1▐ \n §1▐              §9 VISUAL MENU               §1▐ \n §1▐              §9 MOVEMENT MENU             §1▐ \n §1▐              §9 PLAYER MENU                §1▐ \n §1▐               §9WORLD MENU             §1▐ \n §1▐              §9 EXPLOIT MENU             §1▐ \n §1▐              §9 MISC MENU                  §1▐ \n §1▐              §9 FLIES MENU                 §1▐ \n §1▐              §9 GUI MENU                 §1▐ \n §1▐              §9 CREDITS MENU             §1▐ \n §1▐               §cADMIN MENU               §1▐ \n §1▐              §f⋙CLOSE MENU⋘              §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={main=1}] ~~~ execute @s[scores={main_scroll=14..}] ~~~ scoreboard players set @s main_scroll 1

#combat menu scroll
scoreboard objectives add combat_scroll dummy
execute @a[scores={combat=1}] ~~~ execute @s[scores={combat_scroll=1}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §b COMBAT MENU                §1▐ \n §1▐              §9 Killaura                §1▐ \n §1▐               §9Aimbot                     §1▐ \n §1▐               §9CrystalAura                 §1▐ \n §1▐               §9Reach                     §1▐ \n §1▐               §7BowAimbot           §1▐ \n §1▐               §9Hitbox                     §1▐ \n §1▐               §9InfiniteAura               §1▐ \n §1▐               §9AimLock                      §1▐ \n §1▐               §9MultiHit                   §1▐ \n §1▐               §9Teams               §1▐ \n §1▐               §9Close                    §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={combat=1}] ~~~ execute @s[scores={combat_scroll=2}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §b COMBAT MENU                §1▐ \n §1▐              §f⋙Killaura⋘               §1▐ \n §1▐               §9Aimbot                     §1▐ \n §1▐               §9CrystalAura                 §1▐ \n §1▐               §9Reach                     §1▐ \n §1▐               §7BowAimbot           §1▐ \n §1▐               §9Hitbox                     §1▐ \n §1▐               §9InfiniteAura               §1▐ \n §1▐               §9AimLock                      §1▐ \n §1▐               §9 MultiHit                  §1▐ \n §1▐               §9Teams               §1▐ \n §1▐               §9Close                    §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={combat=1}] ~~~ execute @s[scores={combat_scroll=3}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §b COMBAT MENU                §1▐ \n §1▐              §9 Killaura                §1▐ \n §1▐              §f⋙Aimbot⋘                    §1▐ \n §1▐               §9CrystalAura                 §1▐ \n §1▐               §9Reach                     §1▐ \n §1▐               §7BowAimbot           §1▐ \n §1▐               §9Hitbox                     §1▐ \n §1▐               §9InfiniteAura               §1▐ \n §1▐               §9AimLock                      §1▐ \n §1▐               §9 MultiHit                  §1▐ \n §1▐               §9Teams               §1▐ \n §1▐               §9Close                    §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={combat=1}] ~~~ execute @s[scores={combat_scroll=4}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §b COMBAT MENU                §1▐ \n §1▐              §9 Killaura                §1▐ \n §1▐              §9 Aimbot                     §1▐ \n §1▐              §f⋙CrystalAura⋘                §1▐ \n §1▐               §9Reach                     §1▐ \n §1▐               §7BowAimbot           §1▐ \n §1▐               §9Hitbox                     §1▐ \n §1▐               §9InfiniteAura               §1▐ \n §1▐               §9AimLock                      §1▐ \n §1▐               §9 MultiHit                  §1▐ \n §1▐               §9Teams               §1▐ \n §1▐               §9Close                    §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={combat=1}] ~~~ execute @s[scores={combat_scroll=5}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §b COMBAT MENU                §1▐ \n §1▐              §9 Killaura                §1▐ \n §1▐              §9 Aimbot                     §1▐ \n §1▐              §9 CrystalAura                 §1▐ \n §1▐              §f⋙Reach⋘                    §1▐ \n §1▐               §7BowAimbot           §1▐ \n §1▐               §9Hitbox                     §1▐ \n §1▐               §9InfiniteAura               §1▐ \n §1▐               §9AimLock                      §1▐ \n §1▐               §9 MultiHit                  §1▐ \n §1▐               §9Teams               §1▐ \n §1▐               §9Close                    §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={combat=1}] ~~~ execute @s[scores={combat_scroll=6}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §b COMBAT MENU                §1▐ \n §1▐              §9 Killaura                §1▐ \n §1▐              §9 Aimbot                     §1▐ \n §1▐              §9 CrystalAura                 §1▐ \n §1▐              §9 Reach                     §1▐ \n §1▐              §f⋙BowAimbot⋘          §1▐ \n §1▐               §9Hitbox                     §1▐ \n §1▐               §9InfiniteAura               §1▐ \n §1▐               §9AimLock                      §1▐ \n §1▐               §9 MultiHit                  §1▐ \n §1▐               §9Teams               §1▐ \n §1▐               §9Close                    §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={combat=1}] ~~~ execute @s[scores={combat_scroll=7}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §b COMBAT MENU                §1▐ \n §1▐              §9 Killaura                §1▐ \n §1▐              §9 Aimbot                     §1▐ \n §1▐              §9 CrystalAura                 §1▐ \n §1▐              §9 Reach                     §1▐ \n §1▐              §9 BowAimbot           §1▐ \n §1▐              §f⋙Hitbox⋘                    §1▐ \n §1▐               §9InfiniteAura               §1▐ \n §1▐               §9AimLock                      §1▐ \n §1▐               §9 MultiHit                  §1▐ \n §1▐               §9Teams               §1▐ \n §1▐               §9Close                    §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={combat=1}] ~~~ execute @s[scores={combat_scroll=8}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §b COMBAT MENU                §1▐ \n §1▐              §9 Killaura                §1▐ \n §1▐              §9 Aimbot                     §1▐ \n §1▐              §9 CrystalAura                 §1▐ \n §1▐              §9 Reach                     §1▐ \n §1▐              §9 BowAimbot           §1▐ \n §1▐              §9 Hitbox                     §1▐ \n §1▐              §f⋙InfiniteAura⋘              §1▐ \n §1▐               §9AimLock                      §1▐ \n §1▐               §9 MultiHit                  §1▐ \n §1▐               §9Teams               §1▐ \n §1▐               §9Close                    §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={combat=1}] ~~~ execute @s[scores={combat_scroll=9}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §b COMBAT MENU                §1▐ \n §1▐              §9 Killaura                §1▐ \n §1▐              §9 Aimbot                     §1▐ \n §1▐              §9 CrystalAura                 §1▐ \n §1▐              §9 Reach                     §1▐ \n §1▐              §9 BowAimbot           §1▐ \n §1▐              §9 Hitbox                     §1▐ \n §1▐              §9 InfiniteAura               §1▐ \n §1▐              §f⋙AimLock⋘                     §1▐ \n §1▐               §9 MultiHit                  §1▐ \n §1▐               §9Teams               §1▐ \n §1▐               §9Close                    §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={combat=1}] ~~~ execute @s[scores={combat_scroll=10}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §b COMBAT MENU                §1▐ \n §1▐              §9 Killaura                §1▐ \n §1▐              §9 Aimbot                     §1▐ \n §1▐              §9 CrystalAura                 §1▐ \n §1▐              §9 Reach                     §1▐ \n §1▐              §9 BowAimbot           §1▐ \n §1▐              §9 Hitbox                     §1▐ \n §1▐              §9 InfiniteAura               §1▐ \n §1▐              §9 AimLock                      §1▐ \n §1▐              §f⋙MultiHit⋘                  §1▐ \n §1▐               §9Teams               §1▐ \n §1▐               §9Close                    §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={combat=1}] ~~~ execute @s[scores={combat_scroll=11}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §b COMBAT MENU                §1▐ \n §1▐              §9 Killaura                §1▐ \n §1▐              §9 Aimbot                     §1▐ \n §1▐              §9 CrystalAura                 §1▐ \n §1▐              §9 Reach                     §1▐ \n §1▐              §9 BowAimbot           §1▐ \n §1▐              §9 Hitbox                     §1▐ \n §1▐              §9 InfiniteAura               §1▐ \n §1▐              §9 AimLock                      §1▐ \n §1▐              §9 MultiHit                   §1▐ \n §1▐              §f⋙Teams⋘              §1▐ \n §1▐               §9Close                    §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={combat=1}] ~~~ execute @s[scores={combat_scroll=12}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              §b COMBAT MENU                §1▐ \n §1▐              §9 Killaura                §1▐ \n §1▐              §9 Aimbot                     §1▐ \n §1▐              §9 CrystalAura                 §1▐ \n §1▐              §9 Reach                     §1▐ \n §1▐              §9 BowAimbot           §1▐ \n §1▐              §9 Hitbox                     §1▐ \n §1▐              §9 InfiniteAura               §1▐ \n §1▐              §9 AimLock                      §1▐ \n §1▐              §9 MultiHit                   §1▐ \n §1▐              §9 Teams               §1▐ \n §1▐              §9⋙Close⋘                   §1▐ \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ "}]}
execute @a[scores={combat=1}] ~~~ execute @s[scores={combat_scroll=13..}] ~~~ scoreboard players set @s combat_scroll 1

#visual menu scroll
scoreboard objectives add visual_scroll dummy
execute @a[scores={visual=1}] ~~~ execute @s[scores={visual_scroll=1}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={visual=1}] ~~~ execute @s[scores={visual_scroll=2}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={visual=1}] ~~~ execute @s[scores={visual_scroll=3}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={visual=1}] ~~~ execute @s[scores={visual_scroll=4}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={visual=1}] ~~~ execute @s[scores={visual_scroll=5}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={visual=1}] ~~~ execute @s[scores={visual_scroll=6}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={visual=1}] ~~~ execute @s[scores={visual_scroll=7}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={visual=1}] ~~~ execute @s[scores={visual_scroll=8}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={visual=1}] ~~~ execute @s[scores={visual_scroll=9}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={visual=1}] ~~~ execute @s[scores={visual_scroll=10}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐        
execute @a[scores={visual=1}] ~~~ execute @s[scores={visual_scroll=11}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐        
execute @a[scores={visual=1}] ~~~ execute @s[scores={visual_scroll=12}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐        
execute @a[scores={visual=1}] ~~~ execute @s[scores={visual_scroll=13..}] ~~~ scoreboard players set @s visual_scroll 1

#movement menu scroll
scoreboard objectives add movement_scroll dummy
execute @a[scores={movement=1}] ~~~ execute @s[scores={movement_scroll=1}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐     
execute @a[scores={movement=1}] ~~~ execute @s[scores={movement_scroll=2}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐     
execute @a[scores={movement=1}] ~~~ execute @s[scores={movement_scroll=3}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐     
execute @a[scores={movement=1}] ~~~ execute @s[scores={movement_scroll=4}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐     
execute @a[scores={movement=1}] ~~~ execute @s[scores={movement_scroll=5}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐     
execute @a[scores={movement=1}] ~~~ execute @s[scores={movement_scroll=6}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐     
execute @a[scores={movement=1}] ~~~ execute @s[scores={movement_scroll=7}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐     
execute @a[scores={movement=1}] ~~~ execute @s[scores={movement_scroll=8..}] ~~~ scoreboard players set @s movement_scroll 1

#player menu scroll
scoreboard objectives add player_scroll dummy
execute @a[scores={player=1}] ~~~ execute @s[scores={player_scroll=1}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={player=1}] ~~~ execute @s[scores={player_scroll=2}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={player=1}] ~~~ execute @s[scores={player_scroll=3}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={player=1}] ~~~ execute @s[scores={player_scroll=4}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={player=1}] ~~~ execute @s[scores={player_scroll=5}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={player=1}] ~~~ execute @s[scores={player_scroll=6}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={player=1}] ~~~ execute @s[scores={player_scroll=7}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐         
execute @a[scores={player=1}] ~~~ execute @s[scores={player_scroll=8..}] ~~~ scoreboard players set @s player_scroll 1

#world menu scroll
scoreboard objectives add world_scroll dummy
execute @a[scores={world=1}] ~~~ execute @s[scores={world_scroll=1}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐           
execute @a[scores={world=1}] ~~~ execute @s[scores={world_scroll=2}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐           
execute @a[scores={world=1}] ~~~ execute @s[scores={world_scroll=3}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐           
execute @a[scores={world=1}] ~~~ execute @s[scores={world_scroll=4}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐           
execute @a[scores={world=1}] ~~~ execute @s[scores={world_scroll=5}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐           
execute @a[scores={world=1}] ~~~ execute @s[scores={world_scroll=6}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐           
execute @a[scores={world=1}] ~~~ execute @s[scores={world_scroll=7}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐           
execute @a[scores={world=1}] ~~~ execute @s[scores={world_scroll=8..}] ~~~ scoreboard players set @s world_scroll 1

#exploit menu scroll
scoreboard objectives add exploit_scroll dummy
execute @a[scores={exploit=1}] ~~~ execute @s[scores={exploit_scroll=1}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐       
execute @a[scores={exploit=1}] ~~~ execute @s[scores={exploit_scroll=2}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐       
execute @a[scores={exploit=1}] ~~~ execute @s[scores={exploit_scroll=3}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐       
execute @a[scores={exploit=1}] ~~~ execute @s[scores={exploit_scroll=4}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐       
execute @a[scores={exploit=1}] ~~~ execute @s[scores={exploit_scroll=5}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐       
execute @a[scores={exploit=1}] ~~~ execute @s[scores={exploit_scroll=6}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐       
execute @a[scores={exploit=1}] ~~~ execute @s[scores={exploit_scroll=7}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐       
execute @a[scores={exploit=1}] ~~~ execute @s[scores={exploit_scroll=8}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐       
execute @a[scores={exploit=1}] ~~~ execute @s[scores={exploit_scroll=9}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐       
execute @a[scores={exploit=1}] ~~~ execute @s[scores={exploit_scroll=10}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐      
execute @a[scores={exploit=1}] ~~~ execute @s[scores={exploit_scroll=11}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐      
execute @a[scores={exploit=1}] ~~~ execute @s[scores={exploit_scroll=12}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐      
execute @a[scores={exploit=1}] ~~~ execute @s[scores={exploit_scroll=13..}] ~~~ scoreboard players set @s exploit_scroll 1
#misc menu scroll
scoreboard objectives add misc_scroll dummy
execute @a[scores={misc=1}] ~~~ execute @s[scores={misc_scroll=1}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐             
execute @a[scores={misc=1}] ~~~ execute @s[scores={misc_scroll=2}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐             
execute @a[scores={misc=1}] ~~~ execute @s[scores={misc_scroll=3}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐             
execute @a[scores={misc=1}] ~~~ execute @s[scores={misc_scroll=4}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐             
execute @a[scores={misc=1}] ~~~ execute @s[scores={misc_scroll=5}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐             
execute @a[scores={misc=1}] ~~~ execute @s[scores={misc_scroll=6}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐             
execute @a[scores={misc=1}] ~~~ execute @s[scores={misc_scroll=7}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐             
execute @a[scores={misc=1}] ~~~ execute @s[scores={misc_scroll=8..}] ~~~ scoreboard players set @s misc_scroll 1
#gui menu scroll
scoreboard objectives add gui_scroll dummy
#execute @a[scores={gui=1}] ~~~ execute @s[scores={gui_scroll=1}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              
#execute @a[scores={gui=1}] ~~~ execute @s[scores={gui_scroll=2}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              
#execute @a[scores={gui=1}] ~~~ execute @s[scores={gui_scroll=3}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              
#execute @a[scores={gui=1}] ~~~ execute @s[scores={gui_scroll=4}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              
#execute @a[scores={gui=1}] ~~~ execute @s[scores={gui_scroll=5}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              
#execute @a[scores={gui=1}] ~~~ execute @s[scores={gui_scroll=6}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              
#execute @a[scores={gui=1}] ~~~ execute @s[scores={gui_scroll=7}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              
#execute @a[scores={gui=1}] ~~~ execute @s[scores={gui_scroll=8}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              
#execute @a[scores={gui=1}] ~~~ execute @s[scores={gui_scroll=9}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐              
#execute @a[scores={gui=1}] ~~~ execute @s[scores={gui_scroll=10}] ~~~ titleraw @s actionbar {"rawtext":[{"text":"§cLOGGED AS §f⇨ §4"},{"selector":"@s"},{"text":"     §l§bⒸ§dⒶ§bⓀ§dⒺ§bⒹ §dⓊ§bⓅ  \n §1§l ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ ▃▃ \n §1▐             
#execute @a[scores={gui=1}] ~~~ execute @s[scores={gui_scroll=11..}] ~~~ scoreboard players set @s gui_scroll 1
#admin manu scroll
#hide
execute @f ~~~ hide
tag @f[tag=""] add hide